### PR TITLE
chore: bump svm-rs

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
includes 0.8.19 
cc @roynalnaruto 

## PR Checklist

-   [ ] Added Tests
-   [ ] Added Documentation
-   [ ] Updated the changelog
-   [ ] Breaking changes

### CODE REVIEW

**Comment by roynalnaruto** [comment]
Shouldn't the `Cargo.toml` inside `ethers-solc` be updated? @mattsse

**Comment by mattsse** [comment]
good point!
only did cargo update

**Review by roynalnaruto — APPROVED** [review]

**Comment by DrakeEvans** [comment]
@mattsse tests failing

**Comment by mattsse** [comment]
Unrelated 
Cc @gakonst

**Pull request merged**
