### PR TITLE
feat(provider): add RwClient

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Add a Provider that uses a different client for sending tx.

## Solution
Wrap two clients but only the `write` client for ["eth_sendTransaction", "eth_sendRawTransaction"]

## PR Checklist

- [ ] Added Tests
- [x] Added Documentation
- [ ] Updated the changelog

### CODE REVIEW

**Comment by gakonst** [comment]
What would be an example use case of such a client? One would be Flashbots RPC + <Your Node>, anything else in mind?

**Comment by mattsse** [comment]
> What would be an example use case of such a client? One would be Flashbots RPC + , anything else in mind?

yes, this is what I had in mind, not really elaborated, but maybe useful as a starting point

**Comment by meetmangukiya** [comment]
Hi @mattsse, can we get this merged?

**Comment by gakonst** [comment]
@meetmangukiya i'm supportive FWIW, do you also mind sharing your use case?

**Comment by meetmangukiya** [comment]
My use case is also Flashbots RPC

**Comment by mattsse** [comment]
rebased

**Review by gakonst — APPROVED** [review]

**Pull request merged**
