### PR TITLE
feature: bubble up jsonrpc error response via trait

### PR DESCRIPTION
**Pull request by prestwich**
## Motivation

Currently there's no way to get JSON-RPC error response out of the provider or middleware error. They're type-erased in the ProviderError.

## Solution

This adds a `ClientError` trait which helps cast `ProviderError` to `JsonRpcError`. 

I consider this to be a bit of an unpleasant kludge. I'm not sure it should be merged. Hypothetically this would allow us to access and decode revert data from contracts tho, which is definitely a big user need.

## PR Checklist

-   [ ] Added Tests
-   [ ] Added Documentation
-   [ ] Updated the changelog
-   [ ] Breaking changes

### CODE REVIEW

**Comment by prestwich** [comment]
okay this now provides 2 traits:

- `RpcError`, which covers `ProviderError` and all transports
    - exposes `as_error_response` for possible downcast to JsonRpcError 
- `MiddlewareError`  which covers `ProviderError` and up
    - replaces `FromErr` 
    - provides functions for converting to/from Inner
    - provides functions for converting to/from ProviderError
    - provides functions for downcasting to an error response

the core idea here is that `ProviderError` is a hingepoint in the lib. everything below it (except JsonRpcError responses) is implementation details and should be hidden. everything above it is MiddlewareError, and should be stacked like middleware are stacked

if the direction is good, I'll go through and update all the docs

**Comment by prestwich** [comment]
CI failures are unrelated. This is ready for review cc @gakonst @mattsse

**Review by gakonst — APPROVED** [review]
Really nice and useful, basically the same pattern that middleware uses to give access to inner layers but for errors, to avoid the nested match abomination... 

(We could/shoudl've done the refactor in a separate PR but OK w/ me)

**Comment by gakonst** [comment]
Main question is: what breaking changes does this have? Seems like..none? If so, let's go ahead

**Comment by prestwich** [comment]
> (We could/shoudl've done the refactor in a separate PR but OK w/ me)

I can break these into 2 if you want, shoulda done that in the first place tbh

> Main question is: what breaking changes does this have? Seems like..none? If so, let's go ahead

the breaking changes are

- 3rd-party custom transports need to implement `RpcError` for their errors
- 3rd-party custom middleware need to change `FromErr` impls to `MiddlewareError` impls

**Comment by gakonst** [comment]
> 3rd-party custom transports need to implement RpcError for their errors
> 3rd-party custom middleware need to change FromErr impls to MiddlewareError impls

Sounds good. We'll need to update `ethers-flashbots` and `ethers-fireblocks` but otherwise should be good. Let's send it.

**Comment by prestwich** [comment]
re-organization has been moved into #2159

**Comment by prestwich** [comment]
I went ahead and split, as it won't generate conflicts because that branch is based on this one 👍 

I can also easily clean up any conflicts so lfg

**Review by gakonst — APPROVED** [review]

**Review by mattsse — APPROVED** [review]
lgtm, does this affect how the RetryProvider needs to check for serde/reqwest error?

**Comment by prestwich** [comment]
> lgtm, does this affect how the RetryProvider needs to check for serde/reqwest error?

it really doesn't affect it at all. But now that you mention it, we could add `as_serde_error() -> Option<&serde_json::Error>` 🤔

**Comment by prestwich** [comment]
okay I added `as_serde_error()` and `is_*_error()` and a bunch of docs for the traits :)

**Comment by prestwich** [comment]
failures are unrelated and this is good to go 🎉 

like other recent PRs, this is a breaking change, and will require action from 3rd-party crates

**Comment by gakonst** [comment]
supreseded https://github.com/gakonst/ethers-rs/pull/2159

**Pull request closed without merging**
