### PR TITLE
fix: avoid payload moving

### PR DESCRIPTION
**Pull request by imotai**
## PR Checklist

-   [ ] Added Tests
-   [ ] Added Documentation
-   [x] Breaking changes

### CODE REVIEW

**Comment by imotai** [comment]
> 

@prestwich  do you have some ideas about the trait itself should be implemented for &T?

**Review by mattsse — COMMENTED** [review]
considering that this is only a convenience function for `Self::recover(T::encode_eip712)` and `fn encode_eip712(&self` takes self I think only taking a ref would be the more appropriate signature

**Comment by mattsse** [comment]
> Maybe the trait itself should be implemented for `&T`? cc @prestwich

this would be possible with an extension trait, but perhaps not worth it. not sure if the user would have to import that trait as well.

**Comment by prestwich** [comment]
I have no opinion on how this ought to be resolved. The PR as written is a sufficiently minor breaking API change that I would be comfortable with it as a patch release

**Review by DaniPopes — APPROVED** [review]

**Pull request merged**
