### PR TITLE
fix: unify name of supported chains with strum

### PR DESCRIPTION
**Pull request by shawnharmsen**
Opening up a pr to check differences

Related to foundry issue: https://github.com/foundry-rs/foundry/issues/1564
Related pr: https://github.com/foundry-rs/foundry/pull/1581

Current problem is build error:
```sh
➜  ethers-rs git:(add-strum-for-chain) cargo build
   Compiling ethers-core v0.6.0 (/Users/m1/CLionProjects/ethers-rs/ethers-core)
warning: unused import: `VariantNames`
 --> ethers-core/src/types/chain.rs:6:43
  |
6 | use strum::{EnumString, EnumVariantNames, VariantNames};
  |                                           ^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0119]: conflicting implementations of trait `std::str::FromStr` for type `types::chain::Chain`
   --> ethers-core/src/types/chain.rs:15:64
    |
15  | #[derive(Debug, Clone, Copy, Eq, PartialEq, Hash, Deserialize, EnumString, EnumVariantNames)]
    |                                                                ^^^^^^^^^^ conflicting implementation for `types::chain::Chain`
...
132 | impl FromStr for Chain {
    | ---------------------- first implementation here
    |
    = note: this error originates in the derive macro `EnumString` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0119`.
warning: `ethers-core` (lib) generated 1 warning
error: could not compile `ethers-core` due to previous error; 1 warning emitted
warning: build failed, waiting for other jobs to finish...
warning: `ethers-core` (lib) generated 1 warning (1 duplicate)
error: build failed
➜  ethers-rs git:(add-strum-for-chain) 
```

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Updated the changelog

### CODE REVIEW

**Comment by mattsse** [comment]
we already have a `FromStr` impl and can't use `EnumString` here

**Comment by shawnharmsen** [comment]
I think this works

tested locally

- local checkout ethers-rs
- `cargo update -p ethers`
- run `target/debug/forge cache ls -h`

```sh
➜  test3 git:(master) ✗ ~/CLionProjects/foundry/target/debug/forge cache ls -h
forge-cache-ls
Shows cached data from ~/.foundry.

USAGE:
    forge cache ls [CHAINS]...

ARGS:
    <CHAINS>...    [env: CHAIN=] [default: all] [possible values: all, Mainnet, Ropsten, Rinkeby, Goerli, Kovan, XDai, Polygon, Fantom, Dev,
                   FantomTestnet, PolygonMumbai, Avalanche, AvalancheFuji, Sepolia, Moonbeam, MoonbeamDev, Moonriver, Optimism, OptimismKovan,
                   BinanceSmartChain, BinanceSmartChainTestnet, Arbitrum, ArbitrumTestnet, Cronos, CronosTestnet]

OPTIONS:
    -h, --help    Print help information
➜  test3 git:(master) ✗
```

**Comment by shawnharmsen** [comment]
I guess the problem was with snake_case and kebab-case and the outliers `xdai bsc bsc-testnet`

testing locally I get

## help
```sh
➜  test git:(master) ✗ ~/CLionProjects/foundry/target/debug/forge cache ls -h
forge-cache-ls
Shows cached data from ~/.foundry.

USAGE:
    forge cache ls [CHAINS]...

ARGS:
    <CHAINS>...    [env: CHAIN=] [default: all] [possible values: all, mainnet, ropsten, rinkeby,
                   goerli, kovan, xdai, polygon, fantom, dev, fantom-testnet, polygon-mumbai,
                   avalanche, avalanche-fuji, sepolia, moonbeam, moonbeam-dev, moonriver, optimism,
                   optimism-kovan, arbitrum, arbitrum-testnet, cronos, cronos-testnet, bsc, bsc-
                   testnet]

OPTIONS:
    -h, --help    Print help information
➜  test git:(master) ✗
```

## ls default all
and using ls for the problematic ones `xdai` and `bsc` and `bsc-testnet`
- made empty dir for them
- used `forge test --fork-url $RPC_URL --fork-block-number x` for the ones I have alchemy api urls
```sh
➜  test git:(master) ✗ ~/CLionProjects/foundry/target/debug/forge cache ls
-️ rinkeby (6.5 kB)
	-️ Block 1000000 (3.3 kB)
	-️ Block 2000000 (3.3 kB)
-️ xdai (0.0 B)
-️ bsc (0.0 B)
-️ mainnet (3.3 kB)
	-️ Block 2000000 (3.3 kB)
-️ bsc-testnet (0.0 B)
-️ goerli (3.1 kB)
	-️ Block 3000000 (3.1 kB)
➜  test git:(master) ✗


```

## ls individual and multiple

```sh
➜  test git:(master) ✗ ~/CLionProjects/foundry/target/debug/forge cache ls goerli mainnet
-️ goerli (3.1 kB)
	-️ Block 3000000 (3.1 kB)
-️ mainnet (3.3 kB)
	-️ Block 2000000 (3.3 kB)
➜  test git:(master) ✗ ~/CLionProjects/foundry/target/debug/forge cache ls xdai
-️ xdai (0.0 B)
➜  test git:(master) ✗ ~/CLionProjects/foundry/target/debug/forge cache ls bsc
-️ bsc (0.0 B)
➜  test git:(master) ✗ ~/CLionProjects/foundry/target/debug/forge cache ls bsc-testnet
-️ bsc-testnet (0.0 B)
➜  test git:(master) ✗ ~/CLionProjects/foundry/target/debug/forge cache ls fantom
Error:
   0: No such file or directory (os error 2)

Location:
   config/src/lib.rs:995

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
➜  test git:(master) ✗ ~/CLionProjects/foundry/target/debug/forge cache ls optimism-kovan
Error:
   0: No such file or directory (os error 2)

Location:
   config/src/lib.rs:995

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Review by mattsse — APPROVED** [review]
thanks, this is great!

**Review by gakonst — APPROVED** [review]
LGTM - think the Foundry companion is not working yet?

**Pull request merged**
