### PR TITLE
write `CompactContractBytecode` instead of `CompactContract`

### PR DESCRIPTION
**Pull request by brockelmore**
## Motivation
The existing `CompactContract` doesn't have enough information for our needs in foundry. So we write out `CompactContractBytecode` instead which is a slightly stripped down version of `ContractBytecode`. The reason to strip it down is because we lose a decent amount of performance if we write all the other things in `ContractBytecode`. This is a compromise between speed and the needed information.

## Solution

Write `CompactContractBytecode` instead of `CompactContract`

## PR Checklist

- [ ] Added Tests
- [x] Added Documentation
- [ ] Updated the changelog

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
necessary workaround until we find a more flexible solution.

still fails to compile due to changed types.

the `Contracts..` representation is a bit of a mess...

**Comment by brockelmore** [comment]
> still fails to compile due to changed types.

wdym? compiles fine for me?

**Comment by mattsse** [comment]
looks like a doc-test https://github.com/gakonst/ethers-rs/runs/4952579664?check_suite_focus=true#step:9:539

**Comment by brockelmore** [comment]
oh ye the *test* fails, but it compiles okay

**Review by gakonst — APPROVED** [review]
LGTM - we should do a pass at the whole crate to see if we got duplicate functionality / if we can clean things up

**Pull request merged**
