### PR TITLE
fix: rustdoc errors

### LINKED ISSUE #1807: docs.rs failed to build ethers-1.0.0
https://docs.rs/crate/ethers/1.0.0

### PR DESCRIPTION
**Pull request by DaniPopes**
## Motivation

Fixes `rustdoc` warnings and errors ([failed build on docs.rs](https://docs.rs/crate/ethers/1.0.0/builds/656733))

Might close #1807

@gakonst @mattsse

## Solution

Ran this command from project root to abigen Multicall3:

`cargo r -p ethers --example abigen --features ethers-solc -- Multicall3 ethers-contract/tests/solidity-contracts/Multicall.sol ethers-contract/src/multicall/multicall_contract.rs`

## PR Checklist

-   [ ] Added Tests
-   [ ] Added Documentation
-   [ ] Updated the changelog

### CODE REVIEW

**Comment by DaniPopes** [comment]
lint CI fails due to new nightly lints

**Review by mattsse — COMMENTED** [review]
what specific error does this fix and how?

I can see from the logs it wrongly attempts to select `ethers`, but why and how does this PR fix that?

**Comment by mattsse** [comment]
btw it would be great to have a --docs CI workflow.

wanna take this on?

**Comment by DaniPopes** [comment]
> what specific error does this fix and how?
> 
> I can see from the logs it wrongly attempts to select `ethers`, but why and how does this PR fix that?

It's missing some trait imports, I don't know if this will fix every error in the docs.rs build but I can build docs locally with latest nightly and stable

**Comment by gakonst** [comment]
@DaniPopes this has been rebased, can you please resolve the clippy lints? LGTM otherwise and thank you for the patience

**Pull request merged**
