### PR TITLE
ci: mdbook

### PR DESCRIPTION
**Pull request by 0xMelkor**
## Motivation
Provide a CI workflow for the book (continuation of #1994)

## Solution
- [x] Update CI to publish the book on merge
- [ ] Refine the summary and complete the docs 
- [ ] Embed code from the `/examples` folder

## PR Checklist

-   [ ] Added Tests
-   [x] Added Documentation
-   [ ] Updated the changelog
-   [ ] Breaking changes

### CODE REVIEW

**Comment by m0ham3dx** [comment]
There are these two interesting mdbook plugins which I would like to recommend  
1. [`mdbook-admonish`: Callouts](https://lib.rs/crates/mdbook-admonish)  
2. [`mdbook-mermaid:`  Enable Mermaid Diagrams ](https://lib.rs/crates/mdbook-mermaid)

I have personally implemented both in my own work, I am writing this post instead of making a PR because I am slowly gaining familiarity with this whole CI thing, and not entirely sure if it might break your CI. 

Here is an example of what the render looks like - [`HERE`](https://mxw3.m0ham3dx.com/c21)

**Review by gakonst — APPROVED** [review]

**Comment by gakonst** [comment]
Merging so we get the first deploy of the book, and iterate from there.

**Comment by 0xMelkor** [comment]
CI failed to deploy the book
```
Failed to create deployment (status: 404) with build version da0363918b2157f405aed14e940dcf35970bce77. Ensure GitHub Pages has been enabled: https://github.com/gakonst/ethers-rs/settings/pages
```
@gakonst probably  GitHub pages must be enabled. Otherwise I messed up something XD

**Comment by gakonst** [comment]
fixed^^

**Pull request merged**
