### PR TITLE
feat(abigen): support shared type during multiabigen

### LINKED ISSUE #957: Support abigen type deduplication in MultiAbigen
rn type deduplication is a post process step in `abigen!` that does not happen if `Abigen` is invoked programmatically. 
Move type deduplication into core `Abigen` process

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Closes #957

## Solution
move shared types post process to abigen crate.

types that appear in multiple contracts are removed from the contract bindings and put in a separate module (__shared_types for single files and shared_types.rs for multiple files).

Contains Additional refactoring to make this work with the existing `MultiBindings`.
Because the path to `shared_types` depends on whether we're writing to a single file or multiple files we need keep the `ExpandendContract` instead of simply using the final `TokenStream`. To make this work without rewriting it entirely I added another layer
`MultiBindings -> MultiBindingsInner` where `MultiBindingsInner` is the previous implementation + shared type handling. This allows us to not break anything as their interfaces are identical.

since all `MultiBindings` functions require a flag `single_file` we can adjust the path the `shared_types` accordingly before converting everything to `MultiBindingsInner`.

## PR Checklist

- [x] Added Tests
- [x] Added Documentation
- [ ] Updated the changelog

### CODE REVIEW

**Comment by sveitser** [comment]
Sweet. I tried this and the generated bindings look good and compile. 

I'm now getting errors when instantiating contracts but there's a good chance it is user error.

Somehow the inlined ABI seems to be missing the anonymous fields for events. I'm getting

```
panicked at 'invalid abi: Error("missing field `anonymous`", line: 1, column: 548)', src/bindings/mod.rs
```

when trying to instantiate any contract (`MyContract::new(...)`) with events.

If I search the generated bindings file for `anonymous` it does not appear anywhere. The field is there in the ABIs inside the expanded `abigen!` macro.

It's possible my way of loading the abi / bytecode from files is no longer suitable for this workflow.

```rust
async fn load_contract(path: &Path) -> Result<(Abi, BytecodeObject)> {
    let abi_path = path.join("abi.json");
    let bin_path = path.join("bin.txt");

    let abi = ethers::abi::Contract::load(match fs::File::open(&abi_path) {
        Ok(v) => v,
        Err(_) => panic!("Unable to open path {:?}", abi_path),
    })?;

    let bytecode_str = match fs::read_to_string(&bin_path) {
        Ok(v) => v,
        Err(_) => panic!("Unable to read from path {:?}", bin_path),
    };
    let trimmed = bytecode_str.trim().trim_start_matches("0x");
    let bytecode: BytecodeObject = serde_json::from_value(serde_json::json!(trimmed)).unwrap();

    Ok((abi, bytecode))
}
```
But I also tried to use the `CONTRACT_ABI` from the bindings file instead of loading the abi file from disk and I do get the same error.

**Comment by gakonst** [comment]
@sveitser could you pls share which abi you're using to test this?

**Comment by sveitser** [comment]
I made a minimal repro below

```solidity
pragma solidity >=0.8.0;

contract Greeter {
    event MyEvent(uint64 indexed number);

    function greet() public  {
        emit MyEvent(7);
    }
}
```

build.rs:
```rust
use std::path::Path;

use ethers_contract_abigen::MultiAbigen;
use ethers_solc::{Project, ProjectPathsConfig};

fn main() {
    // configure the project with all its paths, solc, cache etc.
    let root = Path::new(&env!("CARGO_MANIFEST_DIR"));
    let config = ProjectPathsConfig::hardhat(root).unwrap();
    println!("{}", config);
    let project = Project::builder().paths(config).build().unwrap();
    let output = project.compile().unwrap();

    if output.has_compiler_errors() {
        for error in output.output().errors {
            println!("{}", error);
        }
        panic!("Solidity compilation errors");
    }
    project.rerun_if_sources_changed();

    let gen = MultiAbigen::from_json_files(root.join("artifacts")).unwrap();
    let bindings = gen.build().unwrap();
    bindings.write_to_module("src/bindings", true).unwrap();
}
```

main.rs:
```rust
use std::sync::Arc;

use ethers::prelude::{rand, Address, Http, LocalWallet, Provider, SignerMiddleware};
pub mod bindings;

fn main() {
    let provider = Provider::<Http>::try_from("http://localhost:8545")
        .expect("could not instantiate HTTP Provider");

    let wallet = LocalWallet::new(&mut rand::thread_rng());
    let client = Arc::new(SignerMiddleware::new(provider, wallet));
    
    // not a valid deployment but enough to trigger the panic
    bindings::Greeter::new(Address::default(), client);
}
```

Generates the following `src/bindings/mod.rs`:
```rust
#![allow(clippy::all)]
//! This module contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! This file may be overwritten by the codegen system at any time.
pub use greeter_mod::*;
#[allow(clippy::too_many_arguments)]
mod greeter_mod {
    #![allow(clippy::enum_variant_names)]
    #![allow(dead_code)]
    #![allow(clippy::type_complexity)]
    #![allow(unused_imports)]
    use ethers::contract::{
        builders::{ContractCall, Event},
        Contract, Lazy,
    };
    use ethers::core::{
        abi::{Abi, Detokenize, InvalidOutputType, Token, Tokenizable},
        types::*,
    };
    use ethers::providers::Middleware;
    #[doc = "Greeter was auto-generated with ethers-rs Abigen. More information at: https://github.com/gakonst/ethers-rs"]
    use std::sync::Arc;
    pub static GREETER_ABI: ethers::contract::Lazy<ethers::core::abi::Abi> =
        ethers::contract::Lazy::new(|| {
            serde_json :: from_str ("[{\"inputs\":[{\"internalType\":\"uint64\",\"name\":\"number\",\"type\":\"uint64\",\"components\":[]}],\"type\":\"event\",\"name\":\"MyEvent\",\"outputs\":[]},{\"inputs\":[],\"stateMutability\":\"nonpayable\",\"type\":\"function\",\"name\":\"greet\",\"outputs\":[]}]") . expect ("invalid abi")
        });
    #[derive(Clone)]
    pub struct Greeter<M>(ethers::contract::Contract<M>);
    impl<M> std::ops::Deref for Greeter<M> {
        type Target = ethers::contract::Contract<M>;
        fn deref(&self) -> &Self::Target {
            &self.0
        }
    }
    impl<M: ethers::providers::Middleware> std::fmt::Debug for Greeter<M> {
        fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
            f.debug_tuple(stringify!(Greeter))
                .field(&self.address())
                .finish()
        }
    }
    impl<'a, M: ethers::providers::Middleware> Greeter<M> {
        #[doc = r" Creates a new contract instance with the specified `ethers`"]
        #[doc = r" client at the given `Address`. The contract derefs to a `ethers::Contract`"]
        #[doc = r" object"]
        pub fn new<T: Into<ethers::core::types::Address>>(
            address: T,
            client: ::std::sync::Arc<M>,
        ) -> Self {
            let contract =
                ethers::contract::Contract::new(address.into(), GREETER_ABI.clone(), client);
            Self(contract)
        }
        #[doc = "Calls the contract's `greet` (0xcfae3217) function"]
        pub fn greet(&self) -> ethers::contract::builders::ContractCall<M, ()> {
            self.0
                .method_hash([207, 174, 50, 23], ())
                .expect("method not found (this should never happen)")
        }
        #[doc = "Gets the contract's `MyEvent` event"]
        pub fn my_event_filter(&self) -> ethers::contract::builders::Event<M, MyEventFilter> {
            self.0.event()
        }
        #[doc = r" Returns an [`Event`](#ethers_contract::builders::Event) builder for all events of this contract"]
        pub fn events(&self) -> ethers::contract::builders::Event<M, MyEventFilter> {
            self.0.event_with_filter(Default::default())
        }
    }
    #[derive(
        Clone,
        Debug,
        Default,
        Eq,
        PartialEq,
        ethers :: contract :: EthEvent,
        ethers :: contract :: EthDisplay,
    )]
    #[ethevent(name = "MyEvent", abi = "MyEvent(uint64)")]
    pub struct MyEventFilter {
        #[ethevent(indexed)]
        pub number: u64,
    }
    #[doc = "Container type for all input parameters for the `greet`function with signature `greet()` and selector `[207, 174, 50, 23]`"]
    #[derive(
        Clone,
        Debug,
        Default,
        Eq,
        PartialEq,
        ethers :: contract :: EthCall,
        ethers :: contract :: EthDisplay,
    )]
    #[ethcall(name = "greet", abi = "greet()")]
    pub struct GreetCall;
}

```

Then `cargo run` fails with
```
thread 'main' panicked at 'invalid abi: Error("missing field `anonymous`", line: 1, column: 133)', src/bindings/mod.rs:26:309
```

**Comment by mattsse** [comment]
@sveitser I think I found the issue, the indexed and anonymous fields were not included in the abi string, could you please try again now?

**Comment by sveitser** [comment]
@mattsse All good now!

**Review by gakonst — APPROVED** [review]

**Pull request merged**
