### PR TITLE
test for trace_callMany

### PR DESCRIPTION
**Pull request by gelfand**
continuation of #792

### CODE REVIEW

**Review by gakonst — CHANGES_REQUESTED** [review]
Looks good, you also need to install Erigon in CI! Will merge after  that

**Comment by gelfand** [comment]
okay, I will prebuilt binaries and upload them to my server, and then just gonna pull them

**Comment by gakonst** [comment]
It might be possible the binary isn't getting detected, or that you're downloading a binary that is not matching the platform of the gha runner?

**Comment by gelfand** [comment]
> It might be possible the binary isn't getting detected, or that you're downloading a binary that is not matching the platform of the gha runner?

I built it for Linux x86-64, tested on another Linux machine even without Go being installed and it was fine.
I'm gonna give a try again to test this binary on freshly installed linux.

**Pull request closed without merging**
