### PR TITLE
feat(core, abi): support shorthand function declarations

### PR DESCRIPTION
**Pull request by shekhirin**
## Motivation

See https://github.com/gakonst/ethers-rs/issues/446

## Solution

Support shorthand function declarations

### CODE REVIEW

**Comment by gakonst** [comment]
This is great. Thank you. Paging @mattsse in case he's available to review this, since he wrote the parser, otherwise I'll try to take a closer look tomorrow.

**Comment by shekhirin** [comment]
Another thing that may worth the issue: redesign human readable ABI parsing, so it doesn't split the strings 9999 times but iterate the tokens instead 😄

**Comment by mattsse** [comment]
Definitely, when I first wrote this I used the internal ethabi parser as the basis for that.
Tokenization would be much nicer, but at least the human readable abi does only add to compile-time in `abigen!` 
+1 for follow up issue, parts of [solang](https://github.com/hyperledger-labs/solang/blob/main/src/parser/lexer.rs) could be useful for that,

**Review by mattsse — APPROVED** [review]
awesome

**Pull request merged**
