### PR TITLE
fix: naming and default impl

### PR DESCRIPTION
**Pull request by roynalnaruto**
## Motivation

Adding some helpers for EvmVersion. Those will be useful when configuring the `SolcConfig` before compiling a `Project`. This is the `ethers-rs` PR to fix https://github.com/gakonst/foundry/issues/202

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Updated the changelog

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
lgtm,
but it seems like the tests using ganache are failing now,
maybe we have to set to instanbul explicitly now?

**Comment by roynalnaruto** [comment]
@mattsse All tests are passing for me. Not sure why those fail in the CI

**Comment by mattsse** [comment]
this looks like a solc issu, emb just a flake.
we run with 0.6.0 currently in CI and the contracts should be supported, they passed in #664 🤔

**Comment by gakonst** [comment]
I'm :+1: to bump Solc in tests

**Pull request merged**
