### PR TITLE
fix bug 2370

### LINKED ISSUE #2370: solc version 0.4.21 does not support Constantinople
**Version**
ethers-solc v2.0.3

**Description**
solc version 0.4.21 does not support Constantinople. 

There was a bug in solc version 0.4.21 and the proper support for constantinoble EVM version was added in version 0.4.22 per
https://github.com/ethereum/solidity/issues/14142#issuecomment-1516171846

The valid version for `CONSTANTINOPLE_SOLC` should be updated

### PR DESCRIPTION
**Pull request by elizabethdinella**
fixes #2370

### CODE REVIEW

**Review by mattsse — CHANGES_REQUESTED** [review]
https://github.com/ethereum/solidity/issues/14142#issuecomment-1516171846

> this error is due to a bug on that release and the proper support for constantinoble EVM version through the command line was only added in version 0.4.22. See: https://github.com/ethereum/solidity/commit/a59d6d2e5303e714a6e66a5d11bd6a9c2e904e4e and https://github.com/ethereum/solidity/pull/3713

nice find! 
please add a short explanation to the docs why we use 0.4.22 but link to the 0.4.21 release:

we have a failing test, could you please check if we need another 0.4.21 constant for this?

> proper support for constantinoble EVM version through the command line was only added in version 0.4.22

I'm not sure if this affects the standard-json input

https://github.com/gakonst/ethers-rs/blob/6ebb1b2337fcc28f6cf3f453bd34deba66e98c1f/ethers-solc/src/artifacts/mod.rs#L758-L760

**Comment by elizabethdinella** [comment]
Can you point me to where to update the docs?

**Review by mattsse — APPROVED** [review]
lgtm

**Comment by prestwich** [comment]
Thanks for the contribution!

> Can you point me to where to update the docs?

Docs can be updated in the `///` rustdoc above the relevant code items

**Pull request merged**
