### PR TITLE
fix: rebase to master for onbjerg's ast

### PR DESCRIPTION
**Pull request by iFrostizz**
## Motivation

Following up on onbjerg's PR: https://github.com/gakonst/ethers-rs/pull/1567 to make the files play nicely with the master branch, the merge from master to the ast branch was deleting some files on the last commit.

## PR Checklist

-   [ ] Check for foundry dependencies (coverage?)

### CODE REVIEW

**Comment by mattsse** [comment]
> > @mattsse @onbjerg let's merge Frostiz's PR on Bjerg's PR and get this in? does it get us tangible improvements on foundry that we should prioritize?


as discussed https://github.com/gakonst/ethers-rs/pull/1567

let's try this, but before we merge let's ensure this doesn't cause issues in foundry.

can you open a PR on foundry with a patch to check this first?

**Comment by iFrostizz** [comment]
> > > @mattsse @onbjerg let's merge Frostiz's PR on Bjerg's PR and get this in? does it get us tangible improvements on foundry that we should prioritize?
> 
> as discussed #1567
> 
> let's try this, but before we merge let's ensure this doesn't cause issues in foundry.
> 
> can you open a PR on foundry with a patch to check this first?

see here: https://github.com/foundry-rs/foundry/pull/3899

**Comment by iFrostizz** [comment]
waiting for https://github.com/foundry-rs/foundry/pull/3899 and this to be merged to master in order to create a new PR for the fixes about the coverage on foundry's side

**Comment by iFrostizz** [comment]
Bump friends

**Comment by gakonst** [comment]
Sorry for being late! Vacation time etc., thanks for the understanding :)

**Comment by iFrostizz** [comment]
All good ! Merry Christmas ⛄

**Pull request merged**
